export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const FETCH_TRACERS_PENDING = 'FETCH_TRACERS_PENDING';
export const FETCH_TRACERS_SUCCESS= 'FETCH_TRACERS_SUCCESS';
export const FETCH_TRACERS_ERROR = 'FETCH_TRACERS_SUCCESS';

export const FETCH_ACCOUNT_SESSIONS_SUCCESS = 'FETCH_ACCOUNT_SESSIONS_SUCCESS';
export const FETCH_ACCOUNT_SESSIONS_PENDING = 'FETCH_ACCOUNT_SESSIONS_PENDING';
export const FETCH_ACCOUNT_SESSIONS_ERROR = 'FETCH_ACCOUNT_SESSIONS_ERROR';
export const UPDATE_TRACING = 'UPDATE_TRACING';