export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const FETCH_TRACERS_PENDING = 'FETCH_TRACERS_PENDING';
export const FETCH_TRACERS_SUCCESS = 'FETCH_TRACERS_SUCCESS';
export const FETCH_TRACERS_ERROR = 'FETCH_TRACERS_ERROR ';

export const FETCH_ACCOUNT_SESSIONS_SUCCESS = 'FETCH_ACCOUNT_SESSIONS_SUCCESS';
export const FETCH_ACCOUNT_SESSIONS_PENDING = 'FETCH_ACCOUNT_SESSIONS_PENDING';
export const FETCH_ACCOUNT_SESSIONS_ERROR = 'FETCH_ACCOUNT_SESSIONS_ERROR';
export const UPDATE_TRACING = 'UPDATE_TRACING';
export const UPDATE_SUSPENDED = 'UPDATE_SUSPENDED';

export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCES';
export const APPLICATION_DELETE = 'APPLICATION_DELETE';
export const LOGOUT = 'LOGOUT';
export const FETCH_PERMISSIONS_SUCCESS = 'FETCH_PERMISSIONS_SUCCESS';
export const SESSION_DELETE = 'SESSION_DELETE';
export const FETCH_PRESENCE_INFO_PENDING = 'FETCH_PRESENCE_INFO_PENDING ';
export const FETCH_PRESENCE_INFO_ERROR = 'FETCH_PRESENCE_INFO_ERROR';
export const FETCH_PRESENCE_INFO_SUCCESS = 'FETCH_PRESENCE_INFO_SUCCESS';

export const FETCH_DOCUMENTS_PENDING = 'FETCH_DOCUMENTS_PENDING';
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMNETS_ERROR = 'FETCH_DOCUMNETS_ERROR';

export const FETCH_ACCOUNTS_PENDING = 'FETCH_ACCOUNTS_PENDING';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_ERROR = 'FETCH_ACCOUNTS_ERROR';

export const FETCH_ACCOUNTS_SEARCH_PENDING = 'FETCH_ACCOUNTS_SEARCH_PENDING';
export const FETCH_ACCOUNTS_SEARCH_SUCCESS = 'FETCH_ACCOUNTS_SSEARCH_UCCESS';
export const FETCH_ACCOUNTS_SEARCH_ERROR = 'FETCH_ACCOUNTS_SEARCH_ERROR';

export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const FETCH_APPLICATIONS_BY_ACCOUNT_PENDING =
  'FETCH_APPLICATIONS_BY_ACCOUNT_PENDING';
export const FETCH_APPLICATIONS_BY_ACCOUNT_SUCCESS =
  'FETCH_APPLICATIONS_BY_ACCOUNT_UCCESS';
export const FETCH_APPLICATIONS_BY_ACCOUNT_ERROR =
  'FETCH_APPLICATIONS_BY_ACCOUNT_ERROR';
