export const SESSION_DATA = 'session_data';
export const PROFILE_DATA = 'profile_data';
export const PERMISSIONS = 'permissions';

export const SESSION_TOKEN = 'session_token';

export const permissionParams = {
  permissions: [
    'ACC_GET_PRESENCE_INFO',
    'ACC_SUSPEND_SESSION',
    'ACC_GET_SESSIONS',
    'ACC_REMOVE_SESSION',
    'ACC_SET_TRACER',
    'ACC_SEARCH_TRACER',
    'ACC_REMOVE_TRACER',
    'ACC_SEARCH_USER',
    'ACC_SET_PASSWORD',
    'ACC_GET_ACCOUNTS',
    'ACC_SYS_MODIFY_USER_MANAGER',
    'ACC_SYS_MODIFY_TRACER_MANAGER',
    'ACC_SYS_MODIFY_PASSPORT_MANAGER',
    'ACC_GET_APPLICATIONS',
    'ACC_GET_DOCUMENTS',
    'ACC_GET_APPLICATIONS_SEARCH',
    'ACC_SET_APPLICATION_STATUS',
    'ACC_SET_DOCUMENT_STATUS',
    'ACC_SET_DOCUMENT_FIELDS',
    'ACC_SET_DOCUMENT_NOTE',
    'ACC_SET_DOCUMENT_TAGS',
    'ACC_GET_DOCUMENT_TYPES',
    'ACC_DELETE_DOCUMENT',
    'ACC_GET_APIKEYS',
    'ACC_UPDATE_APIKEYS',
    'ACC_CREATE_APIKEYS'
  ]
};
