import { CodeCountry } from '@Interfaces/Utils'

export class DataUtil {
  public static countries: CodeCountry[] = [
    {
      code: '93',
      iso: 'AF',
      ru: 'Афганистан',
      en: 'Afghanistan',
    },
    {
      code: '355',
      iso: 'AL',
      ru: 'Албания',
      en: 'Albania',
    },
    {
      code: '213',
      iso: 'DZ',
      ru: 'Алжир',
      en: 'Algeria',
    },
    {
      code: '376',
      iso: 'AD',
      ru: 'Андорра',
      en: 'Andorra',
    },
    {
      code: '244',
      iso: 'AO',
      ru: 'Ангола',
      en: 'Angola',
    },
    {
      code: '672',
      iso: 'AQ',
      ru: 'Антарктида',
      en: 'Antarctica',
    },
    {
      code: '54',
      iso: 'AR',
      ru: 'Аргентина',
      en: 'Argentina',
    },
    {
      code: '374',
      iso: 'AM',
      ru: 'Армения',
      en: 'Armenia',
    },
    {
      code: '297',
      iso: 'AW',
      ru: 'Аруба',
      en: 'Aruba',
    },
    {
      code: '61',
      iso: 'AU',
      ru: 'Австралия',
      en: 'Australia',
    },
    {
      code: '43',
      iso: 'AT',
      ru: 'Австрия',
      en: 'Austria',
    },
    {
      code: '994',
      iso: 'AZ',
      ru: 'Азербайджан',
      en: 'Azerbaijan',
    },
    {
      code: '973',
      iso: 'BH',
      ru: 'Бахрейн',
      en: 'Bahrain',
    },
    {
      code: '880',
      iso: 'BD',
      ru: 'Бангладеш',
      en: 'Bangladesh',
    },
    {
      code: '375',
      iso: 'BY',
      ru: 'Беларусь',
      en: 'Belarus',
    },
    {
      code: '32',
      iso: 'BE',
      ru: 'Бельгия',
      en: 'Belgium',
    },
    {
      code: '501',
      iso: 'BZ',
      ru: 'Белиз',
      en: 'Belize',
    },
    {
      code: '229',
      iso: 'BJ',
      ru: 'Бенин',
      en: 'Benin',
    },
    {
      code: '975',
      iso: 'BT',
      ru: 'Бутан',
      en: 'Bhutan',
    },
    {
      code: '591',
      iso: 'BO',
      ru: 'Боливия',
      en: 'Bolivia',
    },
    {
      code: '387',
      iso: 'BA',
      ru: 'Босния и Герцеговина',
      en: 'Bosnia and Herzegovina',
    },
    {
      code: '267',
      iso: 'BW',
      ru: 'Ботсвана',
      en: 'Botswana',
    },
    {
      code: '55',
      iso: 'BR',
      ru: 'Бразилия',
      en: 'Brazil',
    },
    {
      code: '246',
      iso: 'IO',
      ru: 'Британская территория Индийского океана',
      en: 'British Indian Ocean Territory',
    },
    {
      code: '673',
      iso: 'BN',
      ru: 'Бруней',
      en: 'Brunei',
    },
    {
      code: '359',
      iso: 'BG',
      ru: 'Болгария',
      en: 'Bulgaria',
    },
    {
      code: '226',
      iso: 'BF',
      ru: 'Буркина-Фасо',
      en: 'Burkina Faso',
    },
    {
      code: '257',
      iso: 'BI',
      ru: 'Бурунди',
      en: 'Burundi',
    },
    {
      code: '855',
      iso: 'KH',
      ru: 'Камбоджа',
      en: 'Cambodia',
    },
    {
      code: '237',
      iso: 'CM',
      ru: 'Камерун',
      en: 'Cameroon',
    },
    {
      code: '1',
      iso: 'CA',
      ru: 'Канада',
      en: 'Canada',
    },
    {
      code: '238',
      iso: 'CV',
      ru: 'Кабо-Верде',
      en: 'Cape Verde',
    },
    {
      code: '236',
      iso: 'CF',
      ru: 'Центрально-Африканская Республика',
      en: 'Central African Republic',
    },
    {
      code: '235',
      iso: 'TD',
      ru: 'Чад',
      en: 'Chad',
    },
    {
      code: '56',
      iso: 'CL',
      ru: 'Чили',
      en: 'Chile',
    },
    {
      code: '86',
      iso: 'CN',
      ru: 'Китай',
      en: 'China',
    },
    {
      code: '61',
      iso: 'CX',
      ru: 'Остров Рождества',
      en: 'Christmas Island',
    },
    {
      code: '61',
      iso: 'CC',
      ru: 'Кокосовые острова',
      en: 'Cocos Islands',
    },
    {
      code: '57',
      iso: 'CO',
      ru: 'Колумбия',
      en: 'Colombia',
    },
    {
      code: '269',
      iso: 'KM',
      ru: 'Коморские острова',
      en: 'Comoros',
    },
    {
      code: '682',
      iso: 'CK',
      ru: 'Острова Кука',
      en: 'Cook Islands',
    },
    {
      code: '506',
      iso: 'CR',
      ru: 'Коста-Рика',
      en: 'Costa Rica',
    },
    {
      code: '385',
      iso: 'HR',
      ru: 'Хорватия',
      en: 'Croatia',
    },
    {
      code: '53',
      iso: 'CU',
      ru: 'Куба',
      en: 'Cuba',
    },
    {
      code: '357',
      iso: 'CY',
      ru: 'Кипр',
      en: 'Cyprus',
    },
    {
      code: '420',
      iso: 'CZ',
      ru: 'Чешская Республика',
      en: 'Czech Republic',
    },
    {
      code: '243',
      iso: 'CD',
      ru: 'Демократическая Республика Конго',
      en: 'Democratic Republic of the Congo',
    },
    {
      code: '45',
      iso: 'DK',
      ru: 'Дания',
      en: 'Denmark',
    },
    {
      code: '253',
      iso: 'DJ',
      ru: 'Джибути',
      en: 'Djibouti',
    },
    {
      code: '670',
      iso: 'TL',
      ru: 'Восточный Тимор',
      en: 'East Timor',
    },
    {
      code: '593',
      iso: 'EC',
      ru: 'Эквадор',
      en: 'Ecuador',
    },
    {
      code: '20',
      iso: 'EG',
      ru: 'Египет',
      en: 'Egypt',
    },
    {
      code: '503',
      iso: 'SV',
      ru: 'Сальвадор',
      en: 'El Salvador',
    },
    {
      code: '240',
      iso: 'GQ',
      ru: 'Экваториальная Гвинея',
      en: 'Equatorial Guinea',
    },
    {
      code: '291',
      iso: 'ER',
      ru: 'Эритрея',
      en: 'Eritrea',
    },
    {
      code: '372',
      iso: 'EE',
      ru: 'Эстония',
      en: 'Estonia',
    },
    {
      code: '251',
      iso: 'ET',
      ru: 'Эфиопия',
      en: 'Ethiopia',
    },
    {
      code: '500',
      iso: 'FK',
      ru: 'Фолклендские острова',
      en: 'Falkland Islands',
    },
    {
      code: '298',
      iso: 'FO',
      ru: 'Фарерские острова',
      en: 'Faroe Islands',
    },
    {
      code: '679',
      iso: 'FJ',
      ru: 'Фиджи',
      en: 'Fiji',
    },
    {
      code: '358',
      iso: 'FI',
      ru: 'Финляндия',
      en: 'Finland',
    },
    {
      code: '33',
      iso: 'FR',
      ru: 'Франция',
      en: 'France',
    },
    {
      code: '689',
      iso: 'PF',
      ru: 'Французская Полинезия',
      en: 'French Polynesia',
    },
    {
      code: '241',
      iso: 'GA',
      ru: 'Габон',
      en: 'Gabon',
    },
    {
      code: '220',
      iso: 'GM',
      ru: 'Гамбия',
      en: 'Gambia',
    },
    {
      code: '995',
      iso: 'GE',
      ru: 'Грузия',
      en: 'Georgia',
    },
    {
      code: '49',
      iso: 'DE',
      ru: 'Германия',
      en: 'Germany',
    },
    {
      code: '233',
      iso: 'GH',
      ru: 'Гана',
      en: 'Ghana',
    },
    {
      code: '350',
      iso: 'GI',
      ru: 'Гибралтар',
      en: 'Gibraltar',
    },
    {
      code: '30',
      iso: 'GR',
      ru: 'Греция',
      en: 'Greece',
    },
    {
      code: '299',
      iso: 'GL',
      ru: 'Гренландия',
      en: 'Greenland',
    },
    {
      code: '502',
      iso: 'GT',
      ru: 'Гватемала',
      en: 'Guatemala',
    },
    {
      code: '224',
      iso: 'GN',
      ru: 'Гвинея',
      en: 'Guinea',
    },
    {
      code: '245',
      iso: 'GW',
      ru: 'Гвинея-Бисау',
      en: 'Guinea-Bissau',
    },
    {
      code: '592',
      iso: 'GY',
      ru: 'Гайана',
      en: 'Guyana',
    },
    {
      code: '509',
      iso: 'HT',
      ru: 'Гаити',
      en: 'Haiti',
    },
    {
      code: '504',
      iso: 'HN',
      ru: 'Гондурас',
      en: 'Honduras',
    },
    {
      code: '852',
      iso: 'HK',
      ru: 'Гонконг',
      en: 'Hong Kong',
    },
    {
      code: '36',
      iso: 'HU',
      ru: 'Венгрия',
      en: 'Hungary',
    },
    {
      code: '354',
      iso: 'IS',
      ru: 'Исландия',
      en: 'Iceland',
    },
    {
      code: '91',
      iso: 'IN',
      ru: 'Индия',
      en: 'India',
    },
    {
      code: '62',
      iso: 'ID',
      ru: 'Индонезия',
      en: 'Indonesia',
    },
    {
      code: '98',
      iso: 'IR',
      ru: 'Я побежал',
      en: 'Iran',
    },
    {
      code: '964',
      iso: 'IQ',
      ru: 'Ирак',
      en: 'Iraq',
    },
    {
      code: '353',
      iso: 'IE',
      ru: 'Ирландия',
      en: 'Ireland',
    },
    {
      code: '972',
      iso: 'IL',
      ru: 'Израиль',
      en: 'Israel',
    },
    {
      code: '39',
      iso: 'IT',
      ru: 'Италия',
      en: 'Italy',
    },
    {
      code: '225',
      iso: 'CI',
      ru: "Кот-д'Ивуар",
      en: 'Ivory Coast',
    },
    {
      code: '962',
      iso: 'JO',
      ru: 'Иордания',
      en: 'Jordan',
    },
    {
      code: '7',
      iso: 'KZ',
      ru: 'Казахстан',
      en: 'Kazakhstan',
    },
    {
      code: '254',
      iso: 'KE',
      ru: 'Кения',
      en: 'Kenya',
    },
    {
      code: '686',
      iso: 'KI',
      ru: 'Кирибати',
      en: 'Kiribati',
    },
    {
      code: '383',
      iso: 'XK',
      ru: 'Косово',
      en: 'Kosovo',
    },
    {
      code: '965',
      iso: 'KW',
      ru: 'Кувейт',
      en: 'Kuwait',
    },
    {
      code: '996',
      iso: 'KG',
      ru: 'Киргизия',
      en: 'Kyrgyzstan',
    },
    {
      code: '856',
      iso: 'LA',
      ru: 'Лаос',
      en: 'Laos',
    },
    {
      code: '371',
      iso: 'LV',
      ru: 'Латвия',
      en: 'Latvia',
    },
    {
      code: '961',
      iso: 'LB',
      ru: 'Ливан',
      en: 'Lebanon',
    },
    {
      code: '266',
      iso: 'LS',
      ru: 'Лесото',
      en: 'Lesotho',
    },
    {
      code: '231',
      iso: 'LR',
      ru: 'Либерия',
      en: 'Liberia',
    },
    {
      code: '218',
      iso: 'LY',
      ru: 'Ливия',
      en: 'Libya',
    },
    {
      code: '423',
      iso: 'LI',
      ru: 'Лихтенштейн',
      en: 'Liechtenstein',
    },
    {
      code: '370',
      iso: 'LT',
      ru: 'Литва',
      en: 'Lithuania',
    },
    {
      code: '352',
      iso: 'LU',
      ru: 'Люксембург',
      en: 'Luxembourg',
    },
    {
      code: '853',
      iso: 'MO',
      ru: 'Макао',
      en: 'Macau',
    },
    {
      code: '389',
      iso: 'MK',
      ru: 'Македония',
      en: 'Macedonia',
    },
    {
      code: '261',
      iso: 'MG',
      ru: 'Мадагаскар',
      en: 'Madagascar',
    },
    {
      code: '265',
      iso: 'MW',
      ru: 'Малави',
      en: 'Malawi',
    },
    {
      code: '60',
      iso: 'MY',
      ru: 'Малайзия',
      en: 'Malaysia',
    },
    {
      code: '960',
      iso: 'MV',
      ru: 'Мальдивы',
      en: 'Maldives',
    },
    {
      code: '223',
      iso: 'ML',
      ru: 'Мали',
      en: 'Mali',
    },
    {
      code: '356',
      iso: 'MT',
      ru: 'Мальта',
      en: 'Malta',
    },
    {
      code: '692',
      iso: 'MH',
      ru: 'Маршалловы острова',
      en: 'Marshall Islands',
    },
    {
      code: '222',
      iso: 'MR',
      ru: 'Мавритания',
      en: 'Mauritania',
    },
    {
      code: '230',
      iso: 'MU',
      ru: 'Маврикий',
      en: 'Mauritius',
    },
    {
      code: '262',
      iso: 'YT',
      ru: 'Майотта',
      en: 'Mayotte',
    },
    {
      code: '52',
      iso: 'MX',
      ru: 'Мексика',
      en: 'Mexico',
    },
    {
      code: '691',
      iso: 'FM',
      ru: 'Микронезия',
      en: 'Micronesia',
    },
    {
      code: '373',
      iso: 'MD',
      ru: 'Молдова',
      en: 'Moldova',
    },
    {
      code: '377',
      iso: 'MC',
      ru: 'Монако',
      en: 'Monaco',
    },
    {
      code: '976',
      iso: 'MN',
      ru: 'Монголия',
      en: 'Mongolia',
    },
    {
      code: '382',
      iso: 'ME',
      ru: 'Черногория',
      en: 'Montenegro',
    },
    {
      code: '212',
      iso: 'MA',
      ru: 'Марокко',
      en: 'Morocco',
    },
    {
      code: '258',
      iso: 'MZ',
      ru: 'Мозамбик',
      en: 'Mozambique',
    },
    {
      code: '95',
      iso: 'MM',
      ru: 'Мьянма',
      en: 'Myanmar',
    },
    {
      code: '264',
      iso: 'NA',
      ru: 'Намибия',
      en: 'Namibia',
    },
    {
      code: '674',
      iso: 'NR',
      ru: 'Науру',
      en: 'Nauru',
    },
    {
      code: '977',
      iso: 'NP',
      ru: 'Непал',
      en: 'Nepal',
    },
    {
      code: '31',
      iso: 'NL',
      ru: 'Нидерланды',
      en: 'Netherlands',
    },
    {
      code: '599',
      iso: 'AN',
      ru: 'Нидерландские Антильские острова',
      en: 'Netherlands Antilles',
    },
    {
      code: '687',
      iso: 'NC',
      ru: 'Новая Каледония',
      en: 'New Caledonia',
    },
    {
      code: '64',
      iso: 'NZ',
      ru: 'Новая Зеландия',
      en: 'New Zealand',
    },
    {
      code: '505',
      iso: 'NI',
      ru: 'Никарагуа',
      en: 'Nicaragua',
    },
    {
      code: '227',
      iso: 'NE',
      ru: 'Нигер',
      en: 'Niger',
    },
    {
      code: '234',
      iso: 'NG',
      ru: 'Нигерия',
      en: 'Nigeria',
    },
    {
      code: '683',
      iso: 'NU',
      ru: 'Niue',
      en: 'Niue',
    },
    {
      code: '850',
      iso: 'KP',
      ru: 'Северная Корея',
      en: 'North Korea',
    },
    {
      code: '47',
      iso: 'NO',
      ru: 'Норвегия',
      en: 'Norway',
    },
    {
      code: '968',
      iso: 'OM',
      ru: 'Оман',
      en: 'Oman',
    },
    {
      code: '92',
      iso: 'PK',
      ru: 'Пакистан',
      en: 'Pakistan',
    },
    {
      code: '680',
      iso: 'PW',
      ru: 'Palau',
      en: 'Palau',
    },
    {
      code: '970',
      iso: 'PS',
      ru: 'Палестина',
      en: 'Palestine',
    },
    {
      code: '507',
      iso: 'PA',
      ru: 'Панама',
      en: 'Panama',
    },
    {
      code: '675',
      iso: 'PG',
      ru: 'Папуа - Новая Гвинея',
      en: 'Papua New Guinea',
    },
    {
      code: '595',
      iso: 'PY',
      ru: 'Парагвай',
      en: 'Paraguay',
    },
    {
      code: '51',
      iso: 'PE',
      ru: 'Перу',
      en: 'Peru',
    },
    {
      code: '63',
      iso: 'PH',
      ru: 'Филиппины',
      en: 'Philippines',
    },
    {
      code: '64',
      iso: 'PN',
      ru: 'Питкэрн',
      en: 'Pitcairn',
    },
    {
      code: '48',
      iso: 'PL',
      ru: 'Польша',
      en: 'Poland',
    },
    {
      code: '351',
      iso: 'PT',
      ru: 'Португалия',
      en: 'Portugal',
    },
    {
      code: '974',
      iso: 'QA',
      ru: 'Катар',
      en: 'Qatar',
    },
    {
      code: '242',
      iso: 'CG',
      ru: 'Республика Конго',
      en: 'Republic of the Congo',
    },
    {
      code: '262',
      iso: 'RE',
      ru: 'воссоединение',
      en: 'Reunion',
    },
    {
      code: '40',
      iso: 'RO',
      ru: 'Румыния',
      en: 'Romania',
    },
    {
      code: '7',
      iso: 'ru',
      ru: 'Россия',
      en: 'Russia',
    },
    {
      code: '250',
      iso: 'RW',
      ru: 'Руанда',
      en: 'Rwanda',
    },
    {
      code: '590',
      iso: 'BL',
      ru: 'Сен-Бартельми',
      en: 'Saint Barthelemy',
    },
    {
      code: '290',
      iso: 'SH',
      ru: 'Остров Святой Елены',
      en: 'Saint Helena',
    },
    {
      code: '590',
      iso: 'MF',
      ru: 'Сен-Мартен',
      en: 'Saint Martin',
    },
    {
      code: '508',
      iso: 'PM',
      ru: 'Сен-Пьер и Микелон',
      en: 'Saint Pierre and Miquelon',
    },
    {
      code: '685',
      iso: 'WS',
      ru: 'Самоа',
      en: 'Samoa',
    },
    {
      code: '378',
      iso: 'SM',
      ru: 'Сан-Марино',
      en: 'San Marino',
    },
    {
      code: '239',
      iso: 'ST',
      ru: 'Сан-Томе и Принсипи',
      en: 'Sao Tome and Principe',
    },
    {
      code: '966',
      iso: 'SA',
      ru: 'Саудовская Аравия',
      en: 'Saudi Arabia',
    },
    {
      code: '221',
      iso: 'SN',
      ru: 'Сенегал',
      en: 'Senegal',
    },
    {
      code: '381',
      iso: 'RS',
      ru: 'Сербия',
      en: 'Serbia',
    },
    {
      code: '248',
      iso: 'SC',
      ru: 'Сейшельские острова',
      en: 'Seychelles',
    },
    {
      code: '232',
      iso: 'SL',
      ru: 'Сьерра-Леоне',
      en: 'Sierra Leone',
    },
    {
      code: '65',
      iso: 'SG',
      ru: 'Сингапур',
      en: 'Singapore',
    },
    {
      code: '421',
      iso: 'SK',
      ru: 'Словакия',
      en: 'Slovakia',
    },
    {
      code: '386',
      iso: 'SI',
      ru: 'Словения',
      en: 'Slovenia',
    },
    {
      code: '677',
      iso: 'SB',
      ru: 'Соломоновы острова',
      en: 'Solomon Islands',
    },
    {
      code: '252',
      iso: 'SO',
      ru: 'Сомали',
      en: 'Somalia',
    },
    {
      code: '27',
      iso: 'ZA',
      ru: 'Южная Африка',
      en: 'South Africa',
    },
    {
      code: '82',
      iso: 'KR',
      ru: 'Южная Корея',
      en: 'South Korea',
    },
    {
      code: '211',
      iso: 'SS',
      ru: 'южный Судан',
      en: 'South Sudan',
    },
    {
      code: '34',
      iso: 'ES',
      ru: 'Испания',
      en: 'Spain',
    },
    {
      code: '94',
      iso: 'LK',
      ru: 'Шри-Ланка',
      en: 'Sri Lanka',
    },
    {
      code: '249',
      iso: 'SD',
      ru: 'Судан',
      en: 'Sudan',
    },
    {
      code: '597',
      iso: 'SR',
      ru: 'Суринам',
      en: 'Suriname',
    },
    {
      code: '47',
      iso: 'SJ',
      ru: 'Свальбард и Ян-Майен',
      en: 'Svalbard and Jan Mayen',
    },
    {
      code: '268',
      iso: 'SZ',
      ru: 'Свазиленд',
      en: 'Swaziland',
    },
    {
      code: '46',
      iso: 'SE',
      ru: 'Швеция',
      en: 'Sweden',
    },
    {
      code: '41',
      iso: 'CH',
      ru: 'Швейцария',
      en: 'Switzerland',
    },
    {
      code: '963',
      iso: 'SY',
      ru: 'Сирия',
      en: 'Syria',
    },
    {
      code: '886',
      iso: 'TW',
      ru: 'Тайвань',
      en: 'Taiwan',
    },
    {
      code: '992',
      iso: 'TJ',
      ru: 'Таджикистан',
      en: 'Tajikistan',
    },
    {
      code: '255',
      iso: 'TZ',
      ru: 'Танзания',
      en: 'Tanzania',
    },
    {
      code: '66',
      iso: 'TH',
      ru: 'Таиланд',
      en: 'Thailand',
    },
    {
      code: '228',
      iso: 'TG',
      ru: 'Идти',
      en: 'Togo',
    },
    {
      code: '690',
      iso: 'TK',
      ru: 'Токелау',
      en: 'Tokelau',
    },
    {
      code: '676',
      iso: 'TO',
      ru: 'Тонга',
      en: 'Tonga',
    },
    {
      code: '216',
      iso: 'TN',
      ru: 'Тунис',
      en: 'Tunisia',
    },
    {
      code: '90',
      iso: 'TR',
      ru: 'Турция',
      en: 'Turkey',
    },
    {
      code: '993',
      iso: 'TM',
      ru: 'Туркменистан',
      en: 'Turkmenistan',
    },
    {
      code: '688',
      iso: 'TV',
      ru: 'Тувалу',
      en: 'Tuvalu',
    },
    {
      code: '256',
      iso: 'UG',
      ru: 'Уганда',
      en: 'Uganda',
    },
    {
      code: '380',
      iso: 'UA',
      ru: 'Украина',
      en: 'Ukraine',
    },
    {
      code: '971',
      iso: 'AE',
      ru: 'Объединенные Арабские Эмираты',
      en: 'United Arab Emirates',
    },
    {
      code: '44',
      iso: 'GB',
      ru: 'Великобритания',
      en: 'United Kingdom',
    },
    {
      code: '1',
      iso: 'US',
      ru: 'Соединенные Штаты',
      en: 'United States',
    },
    {
      code: '598',
      iso: 'UY',
      ru: 'Уругвай',
      en: 'Uruguay',
    },
    {
      code: '998',
      iso: 'UZ',
      ru: 'Узбекистан',
      en: 'Uzbekistan',
    },
    {
      code: '678',
      iso: 'VU',
      ru: 'Вануату',
      en: 'Vanuatu',
    },
    {
      code: '379',
      iso: 'VA',
      ru: 'Ватикан',
      en: 'Vatican',
    },
    {
      code: '58',
      iso: 'VE',
      ru: 'Венесуэла',
      en: 'Venezuela',
    },
    {
      code: '84',
      iso: 'VN',
      ru: 'Вьетнам',
      en: 'Vietnam',
    },
    {
      code: '681',
      iso: 'WF',
      ru: 'Уоллис и Футуна',
      en: 'Wallis and Futuna',
    },
    {
      code: '212',
      iso: 'EH',
      ru: 'Западная Сахара',
      en: 'Western Sahara',
    },
    {
      code: '967',
      iso: 'YE',
      ru: 'Йемен',
      en: 'Yemen',
    },
    {
      code: '260',
      iso: 'ZM',
      ru: 'Замбия',
      en: 'Zambia',
    },
    {
      code: '263',
      iso: 'ZW',
      ru: 'Зимбабве',
      en: 'Zimbabwe',
    },
  ]
}
